//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbox_S_Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xbox_S_Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap blankButton {
            get {
                object obj = ResourceManager.GetObject("blankButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BlankFormWIndow {
            get {
                object obj = ResourceManager.GetObject("BlankFormWIndow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Controller_Installer_Shield_Design {
            get {
                object obj = ResourceManager.GetObject("Controller Installer Shield Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dash_plus_Controller_Installer_Shield_Design {
            get {
                object obj = ResourceManager.GetObject("Dash plus Controller Installer Shield Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dashboard_Installer_Shield_Design {
            get {
                object obj = ResourceManager.GetObject("Dashboard Installer Shield Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeltaCompressionDotNet {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeltaCompressionDotNet_MsDelta {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet.MsDelta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeltaCompressionDotNet_PatchApi {
            get {
                object obj = ResourceManager.GetObject("DeltaCompressionDotNet.PatchApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///goto start
        ///
        ///::What this .bat does-
        ///
        ///::Checks for administrator permissions by seeing if we can use `net session`
        ///::then installs ScpVBus 
        ///
        ///:start
        ///echo Administrative permissions required. Checking permissions...
        ///net session &gt;nul 2&gt;&amp;1
        ///if %errorLevel% neq 0 (
        ///    echo Administrative permissions denied. Please launch as an Administrator.
        ///    goto exit
        ///)
        ///
        ///cd %~dp0
        ///
        ///
        ///cls
        ///echo Installing WinUSB drivers for known gamepads (this might take several minutes)
        ///echo.
        ///echo 	Installation Pe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string install_drivers {
            get {
                return ResourceManager.GetString("install drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Installer_Shield_Design_2 {
            get {
                object obj = ResourceManager.GetObject("Installer Shield Design 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libusb_1_0 {
            get {
                object obj = ResourceManager.GetObject("libusb-1.0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_VisualStudio_Interop {
            get {
                object obj = ResourceManager.GetObject("Microsoft.VisualStudio.Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_VisualStudio_OLE_Interop {
            get {
                object obj = ResourceManager.GetObject("Microsoft.VisualStudio.OLE.Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Mono_Cecil {
            get {
                object obj = ResourceManager.GetObject("Mono.Cecil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Mono_Cecil_Mdb {
            get {
                object obj = ResourceManager.GetObject("Mono.Cecil.Mdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Mono_Cecil_Pdb {
            get {
                object obj = ResourceManager.GetObject("Mono.Cecil.Pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Mono_Cecil_Rocks {
            get {
                object obj = ResourceManager.GetObject("Mono.Cecil.Rocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Compute {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Compute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Core {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Graphics {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Input {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Input", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Mathematics {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Mathematics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_OpenAL {
            get {
                object obj = ResourceManager.GetObject("OpenTK.OpenAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Windowing_Common {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Windowing.Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Windowing_Desktop {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Windowing.Desktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OpenTK_Windowing_GraphicsLibraryFramework {
            get {
                object obj = ResourceManager.GetObject("OpenTK.Windowing.GraphicsLibraryFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PInvoke_Windows_Core {
            get {
                object obj = ResourceManager.GetObject("PInvoke.Windows.Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] README {
            get {
                object obj = ResourceManager.GetObject("README", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SharpCompress {
            get {
                object obj = ResourceManager.GetObject("SharpCompress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SharpDX {
            get {
                object obj = ResourceManager.GetObject("SharpDX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SharpDX_RawInput {
            get {
                object obj = ResourceManager.GetObject("SharpDX.RawInput", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SharpDX_XInput {
            get {
                object obj = ResourceManager.GetObject("SharpDX.XInput", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] System_CodeDom {
            get {
                object obj = ResourceManager.GetObject("System.CodeDom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] System_Management {
            get {
                object obj = ResourceManager.GetObject("System.Management", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ViGEmBus_1_21_442_x64_x86_arm64 {
            get {
                object obj = ResourceManager.GetObject("ViGEmBus_1.21.442_x64_x86_arm64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wdi_simple {
            get {
                object obj = ResourceManager.GetObject("wdi-simple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Xb2XInput settings file
        ///#   Reload Xb2XInput for changes to take effect, note that INI filename should match the EXE filename of Xb2XInput!
        ///#   (also make sure Xb2XInput is closed before making any changes, as it may overwrite anything at any time)
        ///#   You can set this file as read-only if you want to prevent any of your settings from being changed.
        ///
        ///[Combinations]
        ///# Button combinations for all XB2X-handled controllers
        ///#   Can be made up of any combination of A/B/X/Y/Start/Back/Up/Down/Left/Right/L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Xb2XInput {
            get {
                return ResourceManager.GetString("Xb2XInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Xb2XInput1 {
            get {
                object obj = ResourceManager.GetObject("Xb2XInput1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Xbox_and_Contrller {
            get {
                object obj = ResourceManager.GetObject("Xbox and Contrller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Xbox_OG_Keyboard_Arrow_KeyUp {
            get {
                object obj = ResourceManager.GetObject("Xbox OG Keyboard Arrow KeyUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] XboxOGKit {
            get {
                object obj = ResourceManager.GetObject("XboxOGKit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] XboxOGKit_deps {
            get {
                object obj = ResourceManager.GetObject("XboxOGKit_deps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;XboxOGKit.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot; /&gt;
        ///        &lt;/sec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XboxOGKit_dll {
            get {
                return ResourceManager.GetString("XboxOGKit_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] XboxOGKit_runtimeconfig {
            get {
                object obj = ResourceManager.GetObject("XboxOGKit_runtimeconfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] XboxOGKit1 {
            get {
                object obj = ResourceManager.GetObject("XboxOGKit1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] XboxOGKit2 {
            get {
                object obj = ResourceManager.GetObject("XboxOGKit2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
